### PR TITLE
Fixed #37

### LINKED ISSUE #37: IsValidRelation returns false for a relation declared without explicit name
For example
```
@relation("s")
struct S
{
	@serial @PK int id;
	mixin RelationMixin;
}
```
will compile just fine, but
```
@relation
struct S
{
	@serial @PK int id;
	mixin RelationMixin;
}
```
won't compile with an error
```
../dpq/source/dpq/mixins.d(32,17): Error: template instance `dpq.relationproxy.RelationProxy!(S)` does not match template declaration `RelationProxy(T)`
  with `T = S`
  must satisfy the following constraint:
`       IsValidRelation!T`
```

### PR DESCRIPTION
**Pull request by Betelgeyser**
Fix for #37. It seems that the problem was with the way how `@relation` was implemented. The detailed explanation what caused an error and how it is fixed is in the changes' comments.

### CODE REVIEW

File: source/dpq/attributes.d [hunk 1]
```diff
@@ -15,10 +15,7 @@ version(unittest) import std.stdio;
    for Connection's ORM functions. If none is set, dpq will
    default to the structure's name in lower_snake_case.
  */
-RelationAttribute relation(string name)
-{
-   return RelationAttribute(name);
-}
```
Comment (Betelgeyser) [inline source/dpq/attributes.d:21]: Since `@relation` UDA was actually a function, `hasUDA!(T, RelationAttribute)` alway returned `false`, because symbols with `@relation` indeed did not aquired `RelationAttribute`. The first solution that comes in mind is using `alias`, but `relation` was a function for a reason and `alias` won't work that simple.

File: source/dpq/attributes.d [hunk 2]
```diff
@@ -221,11 +218,18 @@ template relationName(alias R)
 {
    static if (hasUDA!(R, RelationAttribute))
    {
-      enum rName = getUDAs!(R, RelationAttribute)[0].name;
```
Comment (Betelgeyser) [inline source/dpq/attributes.d:224]: And this is the reason why `alias relation = RelationAttribute` won't work. If UDA is declared with `@relation` instead of `@relation()`, the UDA will be a type, rather than a value. And compilation will fail with `Error: need this for name of type string`.

File: source/dpq/attributes.d [hunk 3]
```diff
@@ -221,11 +218,18 @@ template relationName(alias R)
...
-      static if (rName.length == 0)
+      // check if @relation is a type
+      static if (is(getUDAs!(R, RelationAttribute)[0]))
```
Comment (Betelgeyser) [inline source/dpq/attributes.d:222]: This is the cunning way to check if our `@relation` UDA is a type or is a value.

File: source/dpq/attributes.d [hunk 4]
```diff
@@ -237,10 +241,12 @@ unittest
 
    struct Test {}
    struct someThing {}
+   @relation struct TypeTest {}
    @relation("some_random_name") struct Test2 {}
 
    static assert(relationName!Test == "test");
    static assert(relationName!someThing == "some_thing");
+   static assert(relationName!TypeTest == "type_test");
```
Comment (Betelgeyser) [inline source/dpq/attributes.d:249]: Just a test to test this new case.
